Revert "test-bot: revise Step output transcoding and XML character filtering"
This reverts commit e4583d4d4a3c58e521578dcf777214c9aa4d3a58.

```
==> git clean -ffdx
HEAD is now at e4583d4 test-bot: revise Step output transcoding and XML character filtering
Removing Library/Homebrew/test/.bundle/
Removing Library/Homebrew/test/fs_leak_log
Removing Library/Homebrew/test/vendor/
Error: invalid regular expression: /[^

 -uD7FFuE000-uFFFDu{10000}-u{10FFFF}]/
```
Using Ruby 1.8.