dev-cmd/audit: fix audit annotations
Emitting annotations currently produces:

    Error: no implicit conversion of Symbol into Integer

The issue is that `problem` is an `Array` of problems which we need to
handle individually.