Revert "Enable patchelf.rb for HOMEBREW_DEVELOPERs."
This reverts commit b8ba4444b20726983aec86d36279f56e84b09550.

Fix the error:
brew install patchelf
==> Pouring patchelf-0.10.x86_64_linux.bottle.1.tar.gz
Error: cannot load such file -- patchelf