-Library/Homebrew/shims/mac/super/sed: causes more problems than what it purports to fix
Mountain Lion isn't even supported by Homebrew anymore.

This shim hails back to Homebrew/legacy-homebrew#13787 @MikeMcQuaid

This gets picked up by `configure` scripts (which is fine during builds),
but occasionally gets [baked into binaries][fixincl], triggering:

    Error: Files were found with references to the Homebrew shims directory.

This in turn causes tap maintainers to just override `SED=/usr/bin/sed` for
`configure`, which doesn't always work properly: osx-cross/homebrew-avr#230

Other instances:

 * https://stackoverflow.com/questions/40357246/usr-local-library-homebrew-shims-super-sed-no-such-file-or-directory
 * https://github.com/laruence/yaconf/issues/17
 * https://github.com/Amar1729/homebrew-formulae/issues/1
 * https://blog.logical-dice.com/articles/wp/295

[fixincl]: https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=fixincludes/fixincl.tpl;h=3d70cabc7fd6dd0e63033e6523fac1dca01b285a;hb=HEAD#l42